# Generated by Django 4.0.6 on 2022-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_index', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='shop_index/static/products/%Y/%m/%d'),
        ),
    ]
